In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [ ]:
#print dimensions of a,b, c and 4
print('a dimension', a.ndim)
print('b dimension', b.ndim)
print('c dimension', c.ndim)
print('d dimension', d.ndim)

a dimension 0
b dimension 1
c dimension 2
d dimension 3


In [ ]:
print(c.dtype)
print(d.dtype)

int64
int64


In [ ]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# arange
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#eye function
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#Zeros
np.zeros((5,5),dtype=int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#ones
np.ones((4,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
#full
np.full((4,5),9,dtype=int)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
#diag
x=[444,6,8,9,10,77,22]
np.diag(x)

array([[444,   0,   0,   0,   0,   0,   0],
       [  0,   6,   0,   0,   0,   0,   0],
       [  0,   0,   8,   0,   0,   0,   0],
       [  0,   0,   0,   9,   0,   0,   0],
       [  0,   0,   0,   0,  10,   0,   0],
       [  0,   0,   0,   0,   0,  77,   0],
       [  0,   0,   0,   0,   0,   0,  22]])

In [ ]:
#reshape
x = np.arange(1,13)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [ ]:
n = x.reshape(3,4)
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
n1 = n.reshape(3,2,2)
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
3


In [ ]:
#ravel
m = n.ravel()
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#flatten
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#indexing --1D
a = np.arange(1,12)
print(a)
print(a[5])
print(a[:6])
print(a[::-4])

[ 1  2  3  4  5  6  7  8  9 10 11]
6
[1 2 3 4 5 6]
[11  7  3]


In [ ]:
#indexing --2D
a = np.array([[1,3,5],[2,4,6],[11,22,33]])
print(a)
print([2,0])

[[ 1  3  5]
 [ 2  4  6]
 [11 22 33]]
[2, 0]


In [ ]:
#indexing --3D
a = np.array([[[1,3,5],[2,4,6]],[[111,222,333],[11,22,33]]])
print(a)
#access value 222
print(a[1][0][1])

#access value 11
print(a[1][1][0])

[[[  1   3   5]
  [  2   4   6]]

 [[111 222 333]
  [ 11  22  33]]]
222
11


In [ ]:
#1-D array Slicing
arr = np.arange(1,14)
print(arr)
print(arr[1:6])
print(arr[1:8:2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[2 3 4 5 6]
[2 4 6 8]


In [ ]:
#2-D array slicing
b = np.array([[ 1,3,5],
              [ 2,4,6],
              [11,22,33]])
b
# print(b[0:2,2]) #access[5,6]
# print(b[1:3,0])#access [2,11]
# print(b[2,1:3])#access[22,33]
# print(b[1:,1:]) #access [4,6,22,33]
# print(b[: ,1:3])
# print(b[:,2])
# print(b[:2,0])



array([[ 1,  3,  5],
       [ 2,  4,  6],
       [11, 22, 33]])

In [ ]:
#copy view

x = np.arange(0,14)
x

x1 = x #assign or view both are same

print(x)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [ ]:
x1[1] = 111
print(x1)
print(x)
print(np.shares_memory(x , x1))

[  0 111   2   3   4   5   6   7   8   9  10  11  12  13]
[  0 111   2   3   4   5   6   7   8   9  10  11  12  13]
True


In [ ]:
x2 = x.view()
print(np.shares_memory(x1,x2))

x2[4] =555
print(x)

True
[  0 111   2   3 555   5   6   7   8   9  10  11  12  13]


In [ ]:
x3 = np.copy(x)
# print(x3)
x3[6] =666
print(x3)
print(x)
# np.shares_memory(x3,x)

[  0 111   2   3 555   5 666   7   8   9  10  11  12  13]
[  0 111   2   3 555   5   6   7   8   9  10  11  12  13]


In [ ]:
a = np.array([[ 1,3,5],
              [ 2,4,6],
              [11,22,33]])
a
a>3
a[a > 3]
a[(a>3) & (a<24)]

array([ 5,  4,  6, 11, 22])

In [ ]:
x == x3

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
#transpose
print(a.transpose())

[[ 1  2 11]
 [ 3  4 22]
 [ 5  6 33]]


In [ ]:
#stacking - Horizantal and vertical
# np.vstack((x,x3))
np.hstack((x,x3))


array([  0, 111,   2,   3, 555,   5,   6,   7,   8,   9,  10,  11,  12,
        13,   0, 111,   2,   3, 555,   5, 666,   7,   8,   9,  10,  11,
        12,  13])

In [ ]:
#insert
# np.insert(x3, 4 , x)
print(x3)
np.insert(x, 2 ,[33,999,1000,10000])

[  0 111   2   3 555   5 666   7   8   9  10  11  12  13]


array([    0,   111,    33,   999,  1000, 10000,     2,     3,   555,
           5,     6,     7,     8,     9,    10,    11,    12,    13])

In [ ]:
#delete
np.delete(x3,6 )

array([  0, 111,   2,   3, 555,   5,   7,   8,   9,  10,  11,  12,  13])

In [ ]:
# Mathematical operatipons
a = np.array([[1,3,5],[2,4,6],[11,22,33]])
print(a)

[[ 1  3  5]
 [ 2  4  6]
 [11 22 33]]


In [ ]:
print(np.sin(a))
print(np.cos(a))

[[ 0.84147098  0.14112001 -0.95892427]
 [ 0.90929743 -0.7568025  -0.2794155 ]
 [-0.99999021 -0.00885131  0.99991186]]
[[ 0.54030231 -0.9899925   0.28366219]
 [-0.41614684 -0.65364362  0.96017029]
 [ 0.0044257  -0.99996083 -0.01327675]]


In [ ]:
print(np.tan(a))
# np.tan(45)
np.sin(a) / np.cos(a)

[[ 1.55740772e+00 -1.42546543e-01 -3.38051501e+00]
 [-2.18503986e+00  1.15782128e+00 -2.91006191e-01]
 [-2.25950846e+02  8.85165604e-03 -7.53130148e+01]]


array([[ 1.55740772e+00, -1.42546543e-01, -3.38051501e+00],
       [-2.18503986e+00,  1.15782128e+00, -2.91006191e-01],
       [-2.25950846e+02,  8.85165604e-03, -7.53130148e+01]])

In [ ]:
np.sum(a)
np.sum(a,axis=0)
np.sum(a,axis=1)
np.exp(a)

array([[2.71828183e+00, 2.00855369e+01, 1.48413159e+02],
       [7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [5.98741417e+04, 3.58491285e+09, 2.14643580e+14]])

In [ ]:
np.mean(a)
np.median(a)

np.float64(5.0)

In [ ]:
#Standard deviation
np.std(a)
np.max(a)
np.sort(a)

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [11, 22, 33]])

In [ ]:
#searching function

arr = np.array([11,22,33,44,77,0,1,5,8])
print(arr)
ar1 =np.where(arr > 9)
print(ar1)

[11 22 33 44 77  0  1  5  8]
(array([0, 1, 2, 3, 4]),)


In [ ]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
# Flatten

arr1 = arr.flatten()
print(arr1)
arr1[1] = 200
print(arr1)
print(arr)

[11 22 33 44 77  0  1  5  8]
[ 11 200  33  44  77   0   1   5   8]
[11 22 33 44 77  0  1  5  8]


In [ ]:
# Ravel
arr2 = arr.ravel()
# print(arr2)
arr2[0] = 999
print(arr1)
print(arr2)

[ 11 200  33  44  77   0   1   5   8]
[999  22  33  44  77   0   1   5   8]
